1. 出现下面问题只需要多次重新启动就行。

D:\anaconda3\envs\py308\python.exe E:\Desktop\音乐爬取\获取歌曲详细.py
Traceback (most recent call last):
File "E:\Desktop\音乐爬取\获取歌曲详细.py", line 298, in <module>
music()
File "E:\Desktop\音乐爬取\获取歌曲详细.py", line 54, in __call__
self.get_class_url_list()
File "E:\Desktop\音乐爬取\获取歌曲详细.py", line 35, in get_class_url_list
del class_name_list[0]
IndexError: list assignment index out of range

2. 出现下面问题，请关闭VPN再启动

D:\anaconda3\envs\py308\python.exe E:\Desktop\音乐爬取\获取歌曲详细.py
获取页面失败 https://music.163.com/discover/artist: HTTPSConnectionPool(host='music.163.com', port=443): Max retries exceeded with url: /discover/artist (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1135)')))
Traceback (most recent call last):
File "E:\Desktop\音乐爬取\获取歌曲详细.py", line 298, in <module>
music()
File "E:\Desktop\音乐爬取\获取歌曲详细.py", line 54, in __call__
self.get_class_url_list()
File "E:\Desktop\音乐爬取\获取歌曲详细.py", line 33, in get_class_url_list
class_url_list = html_xml.xpath("//a[@class='cat-flag']/@href")
AttributeError: 'NoneType' object has no attribute 'xpath'